object DependenciesVersions {
    const val APPCOMPAT = "1.6.1"
    const val CARD_VIEW = "1.0.0"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val COROUTINES = "1.7.1"
    const val FRAGMENT_KTX = "1.5.7"
    const val GLIDE = "4.15.1"
    const val HILT = "2.44"
    const val KOTLIN = "1.8.10"
    const val MATERIAL = "1.9.0"
    const val MOSHI = "1.14.0"
    const val NAVIGATION = "2.5.3"
    const val PAGING3 = "3.1.1"
    const val RECYCLE_VIEW = "1.3.0"
    const val RETROFIT = "2.9.0"
    const val SHIMMER = "0.5.0"
    const val STETHO = "1.6.0"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0"
    const val TIMBER = "5.0.1"
}